# Generated by Django 5.2.5 on 2025-10-01 21:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('language', models.ForeignKey(blank=True, db_column='main_language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='core.language', to_field='language_code')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(4)])),
                ('model_used', models.CharField(choices=[('Gemini', 'Gemini'), ('LLAMA', 'LLAMA'), ('GPT', 'GPT')], default='GPT', max_length=10)),
                ('sent_by', models.CharField(choices=[('User', 'User'), ('Bot', 'Bot')], default='User', max_length=10)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='core.conversation')),
                ('language', models.ForeignKey(blank=True, db_column='language_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_lines', to='core.language', to_field='language_code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
