# Generated by Django 5.2.5 on 2025-10-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conversation_conversationline'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversationline',
            constraint=models.CheckConstraint(condition=models.Q(('model_used__in', ['Gemini', 'LLAMA', 'GPT'])), name='check_model_used_enum'),
        ),
        migrations.AddConstraint(
            model_name='conversationline',
            constraint=models.CheckConstraint(condition=models.Q(('sent_by__in', ['User', 'Bot'])), name='check_sent_by_enum'),
        ),
    ]
