# Generated by Django 5.2.5 on 2025-10-02 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversationline_check_model_used_enum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='conversationline',
            name='text',
        ),
        migrations.AddField(
            model_name='conversation',
            name='title_ar',
            field=models.CharField(default='aaaa', max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title_en',
            field=models.CharField(default='aaaa', max_length=100),
        ),
        migrations.AddField(
            model_name='conversationline',
            name='text_ar',
            field=models.TextField(default='aaaa', validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='conversationline',
            name='text_en',
            field=models.TextField(default='aaaa', validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
