# Generated by Django 5.2.5 on 2025-10-03 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_conversation_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_analysis_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_analysis_summary_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='last_analysis_summary_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ConversationAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_lang', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('summary_ar', models.TextField(blank=True, default='')),
                ('summary_en', models.TextField(blank=True, default='')),
                ('detected_language', models.CharField(default='en', max_length=10)),
                ('question_count', models.IntegerField(default=0)),
                ('avg_msg_length', models.FloatField(default=0.0)),
                ('common_topics', models.JSONField(default=list)),
                ('total_conversations', models.IntegerField(default=0)),
                ('total_interactions', models.IntegerField(default=0)),
                ('total_user_messages', models.IntegerField(default=0)),
                ('total_bot_messages', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('conversations', models.ManyToManyField(blank=True, related_name='analyses', to='core.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_conver_user_id_ba278f_idx'), models.Index(fields=['status'], name='core_conver_status_b0e7f4_idx')],
            },
        ),
    ]
