# Generated by Django 5.2.5 on 2025-10-04 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_last_analysis_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationline',
            name='text_html_ar',
            field=models.TextField(default='aaaa', validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='conversationline',
            name='text_html_en',
            field=models.TextField(default='aaaa', validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
