# Generated by Django 5.2.5 on 2025-10-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_conversationline_text_html_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='language',
        ),
        migrations.AddField(
            model_name='user',
            name='conversations_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='conversations_quota',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='last_summary_generated',
            field=models.BooleanField(default=False),
        ),
    ]
