# Generated by Django 5.2.5 on 2025-10-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_conversationline_check_model_used_enum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='conversations_quota',
            field=models.IntegerField(default=5),
        ),
    ]
